# Generated by Django 4.2.2 on 2023-07-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.product')),
            ],
        ),
        migrations.CreateModel(
            name='BakeryItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.bakeryitem')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='bakeryitem',
            name='ingredients',
            field=models.ManyToManyField(through='Bakery.BakeryItemIngredient', to='Bakery.ingredient'),
        ),
    ]
