# Generated by Django 4.2.2 on 2023-07-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
