# Generated by Django 4.2.2 on 2023-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_remove_bakeryitemingredient_quantity_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
