# Generated by Django 4.2.2 on 2023-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0003_alter_orderitem_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryitem',
            name='quantity_percentage',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_percentage',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
