# Generated by Django 4.2.2 on 2023-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0004_remove_bakeryitem_quantity_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryitem',
            name='costPrice',
        ),
        migrations.RemoveField(
            model_name='bakeryitem',
            name='sellingPrice',
        ),
        migrations.AddField(
            model_name='bakeryitemingredient',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bakeryitemingredient',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
