# Generated by Django 4.2.2 on 2023-07-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0007_inventorybakeryitem_inventoryingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='bakeryitemingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.ingredient'),
        ),
    ]
