# Generated by Django 4.2.2 on 2023-07-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0009_bakeryitemingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.bakeryitem')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='Bakery.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='BakeryItemIngredient',
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='ingredients',
            field=models.ManyToManyField(through='Bakery.BakeryItemDetails', to='Bakery.ingredient'),
        ),
    ]
